### ISSUE TITLE
Bot: TicTacToe

### ISSUE THREAD

**Issue by charleso** [charleso/haskell-in-haste#17]
- Medium -> Hard
  - Would almost certainly be impossible to finish in the time given
- Inspired by [well-known FP API design question](http://blog.tmorris.net/posts/understanding-practical-api-design-static-typing-and-functional-programming/)

``` haskell
data Position = NW | N | NE | W | M | E ...
data Board = [(Position, Maybe Move)]
data Player = O | X
data Result = Draw | Won Player

whoWon :: Board -> Maybe Result
move :: Board -> Player -> Position -> Maybe Board
print :: Board -> Text
```

```
/ttt NW

O..
.X.
O..

/ttt W

O..
XX.
O..

/ttt print

O..
XX.
O..
```

**Comment by NaevaTheCat** [comment]
How would you even implement this? Particularly the displaying of results.

**Comment by charleso** [comment]
Apologies, should have put more information. See above with updated description. Basic idea would be to have a (precanned) data type that represents the 9 possible moves, and a board data type. Each move swaps player. You could get fancy and require at least two players and use their username to start the game, but happy to leave that out.

As mention in description, this one isn't quick or easy, but it's a good in that it's pure data structures and isn't trivial. Might be good for anyone who has done some Haskell before.
