### ISSUE TITLE
Bot: Reverse string

### ISSUE THREAD

**Issue by pyko** [charleso/haskell-in-haste#18]
Too simple/boring?

Alternate/related, Is Palindrome Bot

**Comment by charleso** [comment]
In general I don't think there's anything that's too simple/boring. :)

This one does depend on whether the participants will be tempted by the `Prelude.reverse` function or will want to write it themselves? They'll still have to find the function, which will force them to use `ghci` or `hoogle`.

**Comment by charleso** [comment]
Given we're not doing fold or pattern matching of lists I'm going to drop this one for now. Sorry Peggy.
