### ISSUE TITLE
Basic ideas from HaskellForAll

### ISSUE THREAD

**Issue by charleso** [charleso/haskell-in-haste#23]
http://www.haskellforall.com/2015/10/basic-haskell-examples.html

**Comment by NaevaTheCat** [comment]
Cool stuff, I'll have a look this weekend and finish up the bots that penny outlined.

**Comment by charleso** [comment]
Cool. Yeah I've been busy but hoping to finish tic-tac-toe this weekend and/or make the chat room pretty. At some point soon I suspect we can probably draw a line under the bots, at least for now, unless you're really bored. I'll feel bad if you spent lots of time adding bots that never get get a chance to implement on the night. Up to you of course. :)

**Comment by NaevaTheCat** [comment]
It's alright, I feel like it's easier to make a lot of things then actually test them on real people with varying levels of experience to see what works than reason about what might work.

**Comment by charleso** [comment]
I live that blog post, but I'm not sure about any of those examples. My favourite is the TODO list, but I think that the `vote` app is probably close enough not to bother.
