### ISSUE TITLE
Slight hiccup in installation instructions

### ISSUE THREAD

**Issue by benkolera** [charleso/haskell-in-haste#36]
I followed the installation instructions on the readme:
- stack setup
- stack build
- stack ghci 

And got 

```
ben at Bens-MacBook-Pro in ~/src/3rdparty/haskell-in-haste (master)
$ stack ghci
Configuring GHCi with the following packages: haskell-in-haste
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package doctest
    (use -v for more information)
```

Running `stack test` installed doctest and then stack repl worked just fine. 

You may want to get them to run `stack test` as the 2nd step so that everything is installed properly before jumping into ghci. :smile:

**Comment by charleso** [comment]
Fixed https://github.com/charleso/haskell-in-haste/commit/22f373a06ad14555b9e0392c7c16d4ba2377323f

Thanks Ben. :)
