### ISSUE TITLE
Bot: Fibonacci or Pi

### ISSUE THREAD

**Issue by charleso** [charleso/haskell-in-haste#4]
Level: Easy.

Is this too boring/mathsy/silly?

**Comment by NaevaTheCat** [comment]
Canonical fib requires zipwith although there are less nice ways. Zipwith can be funny to get your head around when it's playing with laziness.

Pi to n places is pretty lame but maybe worth having for people who feel very out of depth?

**Comment by charleso** [comment]
I think I'm going to close this. I don't want to add any fuel to the fire that Haskell is just a glorified fibonacci generator. :)
